# Generated by Django 5.0.4 on 2024-11-21 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerSiteCompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, default=None, null=True, upload_to='media/companies/backgroundimages')),
                ('title1', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('title2', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('title3', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company', verbose_name='Company')),
            ],
        ),
    ]
