# Generated by Django 5.0.4 on 2024-11-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_careersitecompanydetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CareerSiteCompanyDetails',
            new_name='CareerSiteCompanyDetail',
        ),
    ]
