# Generated by Django 5.0.4 on 2025-11-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_capturelead_alter_account_role_leadtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='trial_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='trial_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
