# Generated by Django 4.2.23 on 2025-11-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_is_trial_account_trial_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
