# Generated by Django 4.2.23 on 2025-11-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_company_facebook_company_instagram_company_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturelead',
            name='designation',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
