# Generated by Django 4.2.23 on 2025-11-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_capturelead_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/companies/logos'),
        ),
    ]
