# Generated by Django 5.0.4 on 2025-11-17 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_zohotoken'),
        ('hr_services', '0006_schedulecall_company_schedulecall_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZohoCRMHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zohocrmid', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('leadtype', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('contactus', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_services.contactdetails')),
                ('lead', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.capturelead')),
            ],
        ),
    ]
