# Generated by Django 5.0.4 on 2025-11-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_zohocrmhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturelead',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
    ]
