# Generated by Django 4.2.23 on 2025-11-18 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_company_logo'),
        ('account', '0011_capturelead_is_trial'),
    ]

    operations = [
    ]
