# Generated by Django 4.2.23 on 2025-11-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_merge_20251118_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('U', 'User'), ('A', 'Admin'), ('T', 'TrialUser'), ('C', 'Candidate')], default='U', max_length=1),
        ),
    ]
