# Generated by Django 4.2.23 on 2025-12-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='banner',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/companies/banner'),
        ),
    ]
