# Generated by Django 4.2.23 on 2026-02-16 13:15

import common.file_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_company_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, storage=common.file_utils.CompanyFileStorage(), upload_to=common.file_utils.user_photo_path),
        ),
        migrations.AlterField(
            model_name='careersitecompanydetail',
            name='background_image',
            field=models.ImageField(blank=True, default=None, null=True, storage=common.file_utils.CompanyFileStorage(), upload_to=common.file_utils.company_file_path),
        ),
        migrations.AlterField(
            model_name='company',
            name='banner',
            field=models.FileField(blank=True, default=None, null=True, storage=common.file_utils.CompanyFileStorage(), upload_to=common.file_utils.company_banner_path),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, default=None, null=True, storage=common.file_utils.CompanyFileStorage(), upload_to=common.file_utils.company_logo_path),
        ),
    ]
