# Generated by Django 4.2.23 on 2026-02-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_account_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.CharField(blank=True, choices=[('real_estate', 'Real Estate'), ('banking_finance', 'Banking & Finance'), ('construction', 'Construction'), ('arts_entertainment', 'Arts & Entertainment'), ('automotive', 'Automotive'), ('childcare', 'Childcare'), ('healthcare', 'Healthcare'), ('media_pr', 'Media & PR'), ('accounting', 'Accounting'), ('energy', 'Energy'), ('purchasing', 'Purchasing'), ('manufacturing_production', 'Manufacturing & Production'), ('legal', 'Legal'), ('it_software', 'IT & Software'), ('sales', 'Sales'), ('insurance', 'Insurance'), ('human_resources', 'Human Resources'), ('marketing', 'Marketing'), ('retail_wholesale', 'Retail, Wholesale & Stocking'), ('medical', 'Medical'), ('maintenance_installation', 'Installation & Maintenance'), ('mining', 'Mining'), ('civil_engineering', 'Civil Engineering'), ('tourism_hospitality', 'Hospitality & Tourism'), ('project_management', 'Project Management'), ('architecture', 'Architecture'), ('aviation', 'Aviation'), ('catering', 'Catering'), ('chemical_engineering', 'Chemical Engineering'), ('electrical_engineering', 'Electrical Engineering'), ('information_security', 'Information Security'), ('mechanical_engineering', 'Mechanical Engineering'), ('administrative_assistance', 'Administrative Assistance'), ('agriculture_forestry', 'Agriculture & Forestry'), ('apprenticeships_trainee', 'Apprenticeships & Trainee'), ('beauty_wellness', 'Beauty & Wellness'), ('charity_voluntary', 'Charity & Voluntary'), ('cleaning_sanitation', 'Cleaning & Sanitation'), ('customer_service_helpdesk', 'Customer Service & Helpdesk'), ('dental', 'Dental'), ('documentation', 'Documentation'), ('driving_transport', 'Driving & Transport'), ('education_teaching', 'Education & Teaching'), ('fmcg', 'FMCG'), ('government_public_sector', 'Government & Public Sector'), ('graduate', 'Graduate'), ('industrial_engineering', 'Industrial Engineering'), ('logistics_warehousing', 'Logistics & Warehousing'), ('management', 'Management'), ('management_consultancy', 'Management Consultancy'), ('nursing', 'Nursing'), ('oil_gas', 'Oil & Gas'), ('recruitment_consultancy', 'Recruitment Consultancy'), ('scientific_research_development', 'Scientific Research & Development'), ('security_public_safety', 'Security & Public Safety'), ('social_science', 'Social Science'), ('telecoms', 'Telecoms'), ('translation_multilingual', 'Translation & Multilingual'), ('veterinary', 'Veterinary'), ('therapy', 'Therapy'), ('military_public_safety', 'Military & Public Safety'), ('leisure_sports', 'Leisure & Sports'), ('community_social_care', 'Community & Social Care'), ('creative_digital', 'Creative & Digital'), ('ecommerce_social_media', 'E-Commerce & Social Media'), ('pharmaceutical', 'Pharmaceutical'), ('crypto_blockchain', 'Crypto & Blockchain'), ('ai_emerging_technologies', 'AI & Emerging Technologies'), ('sports', 'Sports'), ('hybrid', 'Hybrid'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
