# Generated by Django 4.2.23 on 2026-03-18 10:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_company_sector'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE account_account ALTER COLUMN role TYPE varchar(1)[] USING ARRAY[role]::varchar(1)[];',
            reverse_sql='ALTER TABLE account_account ALTER COLUMN role TYPE varchar(1) USING role[1];'
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('U', 'User'), ('A', 'Admin'), ('T', 'TrialUser'), ('C', 'Candidate')], max_length=1), blank=True, default=list, size=None),
        ),
    ]

