# Generated by Django 4.2.23 on 2026-03-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_ai_letter_site',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_app_site',
            field=models.BooleanField(default=False),
        ),
    ]
