# Generated by Django 4.2.23 on 2026-03-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_account_is_ai_letter_site_account_is_app_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_ai_letter_site',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_app_site',
        ),
        migrations.AddField(
            model_name='company',
            name='is_ai_letter_site',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='is_app_site',
            field=models.BooleanField(default=False),
        ),
    ]
