# Generated by Django 4.2.23 on 2026-02-16 13:15

import common.file_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_city_name_alter_country_name_alter_state_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notetype',
            name='icon',
            field=models.ImageField(blank=True, default=None, null=True, storage=common.file_utils.CompanyFileStorage(), upload_to='companies/icons'),
        ),
    ]
