# Generated by Django 4.2.23 on 2026-02-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_notetype_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notetype',
            name='icon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/data/icons'),
        ),
    ]
