# Generated by Django 5.0.4 on 2024-11-13 13:26

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('candidates', '0001_initial'),
        ('job', '__first__'),
        ('settings', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(choices=[('IP', 'In Person'), ('PC', 'Telephonic'), ('VC', 'Video')], default='IP', max_length=2)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('time_start', models.TimeField(blank=True, default=None, null=True)),
                ('time_end', models.TimeField(blank=True, default=None, null=True)),
                ('interviewers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('email_sub', models.CharField(blank=True, max_length=250, null=True)),
                ('email_msg', models.TextField(blank=True, max_length=5000, null=True)),
                ('document', models.FileField(blank=True, default=None, null=True, upload_to='media/interview/')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate', verbose_name='Candidate')),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.company', verbose_name='Company')),
                ('email_temp', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.emailtemplate', verbose_name='Email Template')),
                ('job', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='job.job', verbose_name='Job')),
                ('location', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.location', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Interview',
                'verbose_name_plural': 'Interviews',
            },
        ),
    ]
