# Generated by Django 5.0.4 on 2024-12-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
        ('settings', '0003_alter_department_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='interviewers',
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewers',
            field=models.ManyToManyField(blank=True, to='settings.contacts'),
        ),
    ]
