# Generated by Django 5.0.4 on 2025-05-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_remove_interview_interviewers_interview_interviewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='webform_interview_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
