# Generated by Django 5.0.4 on 2025-05-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_interview_webform_interview_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='webform_interview_data',
            new_name='dynamic_interview_data',
        ),
    ]
