# Generated by Django 5.0.4 on 2025-10-13 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0021_candidatetimeline_pipeline_stage'),
        ('interview', '0004_rename_webform_interview_data_interview_dynamic_interview_data'),
        ('settings', '0016_emailtemplate_from_email_emailtemplate_reply_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['-created'], 'verbose_name': 'Interview', 'verbose_name_plural': 'Interviews'},
        ),
        migrations.RemoveField(
            model_name='interview',
            name='document',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='email_msg',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='email_sub',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='email_temp',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='type',
        ),
        migrations.AddField(
            model_name='interview',
            name='audit_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='interview',
            name='calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interview',
            name='headless_tokens',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='interview',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('reschedule_requested', 'Reschedule Requested'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=30),
        ),
        migrations.RemoveField(
            model_name='interview',
            name='candidate',
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('by', models.CharField(blank=True, max_length=255, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='interview.interview')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('recommend', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='interview.interview')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='settings.contacts')),
            ],
        ),
        migrations.CreateModel(
            name='RescheduleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_start', models.DateTimeField()),
                ('proposed_end', models.DateTimeField()),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_requests', to='candidates.candidate')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_requests', to='interview.interview')),
            ],
        ),
        migrations.AddField(
            model_name='interview',
            name='candidate',
            field=models.ManyToManyField(blank=True, to='candidates.candidate'),
        ),
    ]
