# Generated by Django 5.0.4 on 2025-10-16 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0021_candidatetimeline_pipeline_stage'),
        ('interview', '0005_alter_interview_options_remove_interview_document_and_more'),
        ('settings', '0016_emailtemplate_from_email_emailtemplate_reply_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='headless_tokens',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='status',
        ),
        migrations.CreateModel(
            name='InterviewCandidateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('reschedule_requested', 'Reschedule Requested'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('headless_token', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_statuses', to='interview.interview')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('reschedule_requested', 'Reschedule Requested'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('headless_token', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer_statuses', to='interview.interview')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.contacts')),
            ],
        ),
    ]
