# Generated by Django 5.0.4 on 2025-10-17 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0021_candidatetimeline_pipeline_stage'),
        ('interview', '0006_remove_interview_headless_tokens_and_more'),
        ('settings', '0016_emailtemplate_from_email_emailtemplate_reply_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclineResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('candidate', 'Candidate'), ('interviewer', 'Interviewer')], max_length=20)),
                ('reason', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decline_responses', to='candidates.candidate')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decline_responses', to='interview.interview')),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decline_responses', to='settings.contacts')),
            ],
        ),
    ]
