# Generated by Django 5.0.4 on 2025-10-17 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0007_declineresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declineresponse',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='declineresponse',
            name='interviewer',
        ),
        migrations.RemoveField(
            model_name='reschedulerequest',
            name='candidate',
        ),
        migrations.AddField(
            model_name='declineresponse',
            name='candidate_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_candidatestatus', to='interview.interviewcandidatestatus'),
        ),
        migrations.AddField(
            model_name='declineresponse',
            name='interviewer_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_interviewerstatus', to='interview.interviewerstatus'),
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='candidate_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reshedule_candidatestatus', to='interview.interviewcandidatestatus'),
        ),
    ]
