# Generated by Django 5.0.4 on 2025-10-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0008_remove_declineresponse_candidate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reschedulerequest',
            name='proposed_end',
        ),
        migrations.RemoveField(
            model_name='reschedulerequest',
            name='proposed_start',
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='proposed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='proposed_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='proposed_timezone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='reschedule_reason_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
