# Generated by Django 4.2.23 on 2025-10-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0009_remove_reschedulerequest_proposed_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('reschedule_requested', 'Reschedule Requested'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=30),
        ),
    ]
