# Generated by Django 4.2.23 on 2025-10-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0010_interview_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reschedulerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('interviewer_email_send', 'Interviewer Email Send')], default='pending', max_length=50),
        ),
    ]
