# Generated by Django 4.2.23 on 2025-10-27 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0021_candidatetimeline_pipeline_stage'),
        ('interview', '0011_alter_reschedulerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='candidates.candidate'),
        ),
    ]
