# Generated by Django 4.2.23 on 2025-10-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0012_feedback_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
