# Generated by Django 5.0.4 on 2025-10-29 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0013_feedback_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='reschedulerequest',
            name='actor_type',
            field=models.CharField(blank=True, choices=[('candidate', 'Candidate'), ('interviewer', 'Interviewer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='interviewer_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reshedule_interviewerstatus', to='interview.interviewerstatus'),
        ),
    ]
