# Generated by Django 4.2.23 on 2025-09-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='Jd_create',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='mobile_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
