# Generated by Django 4.2.23 on 2025-09-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_services', '0002_contactdetails_jd_create_alter_contactdetails_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='Jd_create',
            field=models.IntegerField(default=1),
        ),
    ]
