# Generated by Django 4.2.23 on 2025-09-29 11:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr_services', '0003_alter_contactdetails_jd_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mobile_number', models.BigIntegerField(unique=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
