# Generated by Django 4.2.23 on 2025-09-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_services', '0004_schedulecall'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='unsubscribe',
            field=models.BooleanField(default=False),
        ),
    ]
