# Generated by Django 4.2.23 on 2025-10-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_services', '0005_contactdetails_unsubscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulecall',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedulecall',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='schedulecall',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedulecall',
            name='platform',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
