# Generated by Django 5.0.4 on 2024-11-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_skill_subjectspecialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subjectspecialization',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
