# Generated by Django 5.0.4 on 2024-12-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidatewithoutlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatewithoutlogin',
            name='login_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
