# Generated by Django 5.0.4 on 2024-12-17 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_candidatewithoutlogin_login_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='current_job_title',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='professional_degree',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='subjects',
        ),
    ]
