# Generated by Django 5.0.4 on 2024-12-17 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_remove_candidate_current_job_title_and_more'),
        ('settings', '0004_alter_contacts_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='current_job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.designation', verbose_name='Designation'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='professional_degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.degree', verbose_name='Degree'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.ManyToManyField(blank=True, to='candidates.skill'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='candidates.subjectspecialization'),
        ),
    ]
