# Generated by Django 5.0.4 on 2025-01-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_candidate_current_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume_user',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
