# Generated by Django 5.0.4 on 2025-01-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_candidate_resume_id_candidate_resume_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='resume_id',
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
