# Generated by Django 5.0.4 on 2025-01-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_remove_candidate_resume_id_candidate_resume_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='email_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='email_tls',
            field=models.BooleanField(default=True),
        ),
    ]
