# Generated by Django 5.0.4 on 2025-01-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_emailsettings_email_ssl_emailsettings_email_tls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='email_host',
            field=models.CharField(max_length=255),
        ),
    ]
