# Generated by Django 5.0.4 on 2025-01-31 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0011_alter_emailsettings_email_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='skills',
        ),
    ]
