# Generated by Django 5.0.4 on 2025-01-31 06:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_remove_candidate_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
