# Generated by Django 5.0.4 on 2025-03-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0013_candidate_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='current_salary',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='expected_salary',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='salary_currency',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='professional_certificate',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
