# Generated by Django 5.0.4 on 2025-04-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0014_candidate_current_salary_candidate_expected_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='webform_candidate_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
