# Generated by Django 5.0.4 on 2025-05-01 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0015_candidate_webform_candidate_data'),
        ('settings', '0009_alter_webform_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='webform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.webform'),
        ),
    ]
