# Generated by Django 5.0.4 on 2025-06-30 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_company_admin'),
        ('candidates', '0017_candidatetimeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.company', verbose_name='Company'),
        ),
    ]
