# Generated by Django 5.0.4 on 2025-07-04 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_company_admin'),
        ('candidates', '0018_candidate_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company', verbose_name='company'),
        ),
    ]
