# Generated by Django 4.2.23 on 2025-08-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0020_dailyemailquota'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatetimeline',
            name='pipeline_stage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
