# Generated by Django 4.2.23 on 2025-11-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0031_alter_job_assesment_alter_job_department_and_more'),
        ('candidates', '0022_alter_candidate_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='job',
            field=models.ManyToManyField(blank=True, related_name='candidates', to='job.job', verbose_name='Job'),
        ),
    ]
