# Generated by Django 4.2.23 on 2025-11-19 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidates', '0023_alter_candidate_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='account',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Account'),
        ),
    ]
