# Generated by Django 4.2.23 on 2025-11-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0026_candidateresume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateresume',
            name='resume',
            field=models.FileField(upload_to='media/resumes/'),
        ),
    ]
