# Generated by Django 4.2.23 on 2026-01-08 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0031_coresignalcandidatestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rjmsanalysis',
            name='sms_score',
        ),
    ]
