# Generated by Django 4.2.23 on 2026-01-16 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0032_remove_rjmsanalysis_sms_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoresignalCandidateStatus',
        ),
    ]
