# Generated by Django 4.2.23 on 2026-01-16 10:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_company_banner'),
        ('candidates', '0033_delete_coresignalcandidatestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoresignalCandidateStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('sortlisted', 'Sortlisted'), ('rejected', 'Rejected')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.company')),
                ('coresignal_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.coresignalpreview')),
            ],
        ),
    ]
