# Generated by Django 4.2.23 on 2026-01-19 11:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_company_banner'),
        ('candidates', '0034_coresignalcandidatestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoresignalCandidateVisiteCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company', verbose_name='Company')),
                ('visitescandidatelist', models.ManyToManyField(to='candidates.coresignalpreview', verbose_name='Visited Candidates')),
            ],
        ),
    ]
