# Generated by Django 4.2.23 on 2026-01-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0035_coresignalcandidatevisitecompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresignalpreview',
            name='is_list',
            field=models.BooleanField(default=True),
        ),
    ]
