# Generated by Django 4.2.23 on 2026-02-16 13:15

import common.file_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0036_coresignalpreview_is_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='certificate',
            field=models.FileField(blank=True, default=None, null=True, storage=common.file_utils.CompanyFileStorage(), upload_to=common.file_utils.certificate_upload_path),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cover_letter',
            field=models.FileField(blank=True, default=None, null=True, storage=common.file_utils.CompanyFileStorage(), upload_to=common.file_utils.cover_letter_path),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, default=None, null=True, storage=common.file_utils.CompanyFileStorage(), upload_to=common.file_utils.resume_upload_path),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, storage=common.file_utils.CompanyFileStorage(), upload_to='candidates/profile_photos'),
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='resume',
            field=models.FileField(blank=True, null=True, storage=common.file_utils.CompanyFileStorage(), upload_to='candidates/resumes'),
        ),
        migrations.AlterField(
            model_name='candidatewithoutlogin',
            name='certificate',
            field=models.FileField(blank=True, null=True, storage=common.file_utils.CompanyFileStorage(), upload_to='candidates/certificates'),
        ),
        migrations.AlterField(
            model_name='candidatewithoutlogin',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, storage=common.file_utils.CompanyFileStorage(), upload_to='candidates/cover_letters'),
        ),
        migrations.AlterField(
            model_name='candidatewithoutlogin',
            name='professional_certificate',
            field=models.FileField(blank=True, null=True, storage=common.file_utils.CompanyFileStorage(), upload_to='candidates/professional_certificates'),
        ),
    ]
