# Generated by Django 4.2.23 on 2026-02-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0037_alter_candidate_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_photos/'),
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='resume',
            field=models.FileField(upload_to='media/resumes/'),
        ),
        migrations.AlterField(
            model_name='candidatewithoutlogin',
            name='certificate',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/resume/'),
        ),
        migrations.AlterField(
            model_name='candidatewithoutlogin',
            name='cover_letter',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/cover_letter/'),
        ),
    ]
