# Generated by Django 4.2.23 on 2026-04-23 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0035_alter_templatejob_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidates', '0038_alter_candidateprofile_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatetimeline',
            name='job',
            field=models.ManyToManyField(blank=True, to='job.job'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('todo_type', models.CharField(blank=True, choices=[('TASKS', 'Tasks'), ('EVENTS', 'Events'), ('CALLS', 'Calls')], max_length=50, null=True)),
                ('related_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
