# Generated by Django 4.2.23 on 2026-04-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0039_alter_candidatetimeline_job_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='reminder_alert_type',
            field=models.CharField(blank=True, choices=[('EMAIL', 'email'), ('POP-UP', 'pop-up')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='reminder_alert_type',
            field=models.CharField(blank=True, choices=[('EMAIL', 'email'), ('POP-UP', 'pop-up')], max_length=20, null=True),
        ),
    ]
