# Generated by Django 4.2.23 on 2026-04-30 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_remove_account_is_ai_letter_site_and_more'),
        ('candidates', '0040_call_reminder_alert_type_events_reminder_alert_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='account.company'),
        ),
    ]
