# Generated by Django 4.2.23 on 2026-03-06 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0016_company_sector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_type', models.CharField(choices=[('offer', 'Offer Letter'), ('appointment', 'Appointment Letter'), ('confirmation', 'Confirmation Letter'), ('experience', 'Experience Letter'), ('increment', 'Increment Letter'), ('relieving', 'Relieving Letter'), ('leave_policy', 'Leave Policy'), ('wfh_policy', 'WFH/Hybrid Policy'), ('freelancer_contract', 'Freelancer Contract'), ('nda', 'NDA'), ('onboarding', 'Onboarding Plan'), ('evp', 'EVP Builder'), ('employer_branding', 'Employer Branding Post')], max_length=50)),
                ('candidate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('input_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_letters', to='account.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
