# Generated by Django 4.2.23 on 2026-03-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedletter',
            name='letter_type',
            field=models.CharField(choices=[('offer', 'Offer Letter'), ('appointment', 'Appointment Letter'), ('confirmation', 'Confirmation Letter'), ('experience', 'Experience Letter'), ('increment', 'Increment Letter'), ('relieving', 'Relieving Letter'), ('leave_policy', 'Leave Policy'), ('wfh_policy', 'WFH/Hybrid Policy'), ('freelancer_contract', 'Freelancer Contract'), ('nda', 'NDA'), ('onboarding', 'Onboarding Plan'), ('evp', 'EVP Builder'), ('branding_post', 'Employer Branding Post')], max_length=50),
        ),
    ]
