# Generated by Django 4.2.23 on 2026-03-09 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_company_sector'),
        ('letters', '0002_alter_generatedletter_letter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedletter',
            name='letter_category',
            field=models.CharField(blank=True, choices=[('letters', 'Letters'), ('policies', 'Policies'), ('contracts', 'Contracts'), ('employerbranding', 'Employer Branding')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='LetterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signatory_name', models.CharField(blank=True, max_length=255, null=True)),
                ('signatory_title', models.CharField(blank=True, max_length=255, null=True)),
                ('signatory_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('signatory_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('show_company_logo', models.BooleanField(default=True)),
                ('show_company_name', models.BooleanField(default=True)),
                ('show_release_date', models.BooleanField(default=True)),
                ('header_tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('header_background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('show_address', models.BooleanField(default=True)),
                ('show_contact_details', models.BooleanField(default=True)),
                ('custom_footer_text', models.TextField(blank=True, null=True)),
                ('footer_background_color', models.CharField(default='#F5F5F5', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='letter_settings', to='account.company')),
            ],
        ),
    ]
