# Generated by Django 4.2.23 on 2026-03-24 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_remove_account_is_ai_letter_site_and_more'),
        ('letters', '0003_generatedletter_letter_category_lettersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterCreditPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('credits', models.PositiveIntegerField(help_text='Number of letter generation credits this package gives.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Base price in INR (excl. GST).', max_digits=10)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price in INR (excl. GST). Leave blank for no discount.', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='letters.lettercreditpackage')),
            ],
        ),
        migrations.CreateModel(
            name='LetterCreditWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_credits', models.PositiveIntegerField(default=0, help_text='Total credits ever added (purchases).')),
                ('used_credits', models.PositiveIntegerField(default=0, help_text='Total credits consumed (letter generations).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='letter_credit_wallet', to='account.company')),
            ],
        ),
        migrations.CreateModel(
            name='LetterCreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('deduction', 'Deduction')], max_length=20)),
                ('credits', models.PositiveIntegerField(help_text='Credits added (purchase) or consumed (deduction).')),
                ('letter_type', models.CharField(blank=True, help_text="Letter type for deduction transactions (e.g. 'offer').", max_length=50, null=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid in INR (incl. GST), for purchase transactions.', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_credit_transactions', to='account.company')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='letters.lettercreditpackage')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='letters.lettercreditwallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
