# Generated by Django 4.2.23 on 2026-03-24 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0004_lettercreditpackage_payment_lettercreditwallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettercredittransaction',
            name='letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='letters.generatedletter'),
        ),
    ]
