# Generated by Django 4.2.23 on 2026-03-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0006_toolrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettersettings',
            name='useCompanyContext',
            field=models.BooleanField(default=True),
        ),
    ]
