# Generated by Django 4.2.23 on 2026-03-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0007_lettersettings_usecompanycontext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatedletter',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='lettercredittransaction',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='generatedletter',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='lettercreditpackage',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='lettercreditpackage',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='lettercredittransaction',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='lettercreditwallet',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='lettercreditwallet',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='lettersettings',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='lettersettings',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='toolrequest',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AddField(
            model_name='generatedletter',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lettercredittransaction',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='toolrequest',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
