# Generated by Django 4.2.23 on 2026-03-31 11:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_remove_account_is_ai_letter_site_and_more'),
        ('letters', '0008_alter_generatedletter_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiIntegrationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('platform', models.CharField(blank=True, help_text='Platform name', max_length=255, null=True)),
                ('ai_tool', models.CharField(blank=True, help_text='AI tool name', max_length=255, null=True)),
                ('note', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_integration_requests', to='account.company')),
            ],
            options={
                'verbose_name': 'API Integration Request',
                'verbose_name_plural': 'API Integration Requests',
                'ordering': ['-created'],
            },
        ),
    ]
