# Generated by Django 4.2.23 on 2026-03-31 11:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0009_apiintegrationrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiintegrationrequest',
            name='ai_tool',
        ),
        migrations.RemoveField(
            model_name='apiintegrationrequest',
            name='company',
        ),
        migrations.AddField(
            model_name='apiintegrationrequest',
            name='ai_tools',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, help_text='List of AI tools', null=True, size=None),
        ),
    ]
