# Generated by Django 5.0.4 on 2024-11-19 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('settings', '0002_alter_degree_company_alter_department_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company', verbose_name='Company'),
        ),
    ]
