# Generated by Django 5.0.4 on 2024-12-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_department_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
