# Generated by Django 5.0.4 on 2025-01-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_contacts_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email_host', models.CharField(blank=True, max_length=100, null=True)),
                ('Email_port', models.CharField(blank=True, max_length=100, null=True)),
                ('Email_use_tls', models.BooleanField(default=True)),
                ('Email_use_ssl', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
