# Generated by Django 5.0.4 on 2025-01-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_emailcredentials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailCredentials',
            new_name='EmailCredential',
        ),
    ]
