# Generated by Django 5.0.4 on 2025-04-11 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_company_admin'),
        ('settings', '0007_alter_emailcategory_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('module_type', models.CharField(choices=[('job_opening', 'Job Opening'), ('candidate', 'Candidate'), ('interview', 'Interview')])),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('form', models.JSONField(default=None, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company', verbose_name='Company')),
            ],
        ),
        migrations.AddField(
            model_name='webform',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.module'),
        ),
    ]
