# Generated by Django 5.0.4 on 2025-05-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_alter_webform_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_type',
            field=models.CharField(choices=[('job_opening', 'Job Opening'), ('candidate', 'Candidate'), ('interview', 'Interview'), ('assessment', 'Assessment')]),
        ),
    ]
