# Generated by Django 5.0.4 on 2025-07-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_alter_module_module_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='unsubscribe_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Unsubscribe Link'),
        ),
    ]
