# Generated by Django 5.0.4 on 2025-07-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_remove_emailtemplate_unsubscribe_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='add_signature',
            field=models.BooleanField(default=False, verbose_name='Add Signature'),
        ),
    ]
