# Generated by Django 5.0.4 on 2025-07-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_emailtemplate_add_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='attachment_category',
            field=models.CharField(blank=True, choices=[('job_openings', 'Job Openings'), ('candidates', 'Candidates')], max_length=50, null=True, verbose_name='Attachment Category'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='attachment_subcategory',
            field=models.CharField(blank=True, choices=[('job_document', 'Job Document'), ('resume', 'Resume'), ('certificate', 'Certificate'), ('cover_letter', 'Cover Letter')], max_length=50, null=True, verbose_name='Attachment Subcategory'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='unsubscribe_link',
            field=models.BooleanField(default=False),
        ),
    ]
