# Generated by Django 5.0.4 on 2025-07-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_emailtemplate_attachment_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='footer',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Footer'),
        ),
    ]
