# Generated by Django 5.0.4 on 2025-07-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_emailtemplate_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='From Email'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='reply_to',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Reply To Email'),
        ),
    ]
