# Generated by Django 4.2.23 on 2025-11-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0017_shortlink_qrmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrmodel',
            name='update_at',
        ),
        migrations.AddField(
            model_name='qrmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='qrmodel',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/qr_codes/'),
        ),
    ]
