# Generated by Django 4.2.23 on 2025-12-10 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_company_banner'),
        ('settings', '0018_remove_qrmodel_update_at_qrmodel_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkdingCompanyid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkding_id', models.CharField(help_text='Company ID from Linkding service', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata from Linkding', null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkding_ids', to='account.company')),
            ],
        ),
    ]
