# Generated by Django 4.2.23 on 2026-02-03 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_company_banner'),
        ('settings', '0021_candidateevaluationcriteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobBoardList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=400)),
                ('logo', models.FileField(blank=True, null=True, upload_to='media/job_board_list/logo/')),
                ('value', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_boards', to='account.company')),
                ('job_board_list', models.ManyToManyField(related_name='values', to='settings.jobboardlist')),
            ],
        ),
    ]
