# Generated by Django 4.2.23 on 2026-02-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0022_jobboardlist_jobboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
