# Generated by Django 4.2.23 on 2026-02-09 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_company_banner'),
        ('settings', '0025_billingcycle_feature_payment_plan_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credithistory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
    ]
