# Generated by Django 4.2.23 on 2026-02-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0026_credithistory_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditwallet',
            name='iswithoutcredit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feature',
            name='iswithoutcredit',
            field=models.BooleanField(default=False),
        ),
    ]
