# Generated by Django 4.2.23 on 2026-02-11 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0027_creditwallet_iswithoutcredit_feature_iswithoutcredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billingcycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.billingcycle'),
        ),
    ]
