# Generated by Django 4.2.23 on 2026-02-11 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0029_remove_subscription_billingcycle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilinghistory',
            name='plan',
        ),
        migrations.AddField(
            model_name='bilinghistory',
            name='plan_pricing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.planpricing'),
        ),
    ]
