# Generated by Django 4.2.23 on 2026-02-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0030_remove_bilinghistory_plan_bilinghistory_plan_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditwallet',
            name='total_credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='creditwallet',
            name='used_credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planfeaturecredit',
            name='credit_limit',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
