# Generated by Django 4.2.23 on 2026-02-16 13:15

import common.file_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0031_alter_creditwallet_total_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrmodel',
            name='qr_image',
            field=models.ImageField(blank=True, default=None, null=True, storage=common.file_utils.CompanyFileStorage(), upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='Profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, storage=common.file_utils.CompanyFileStorage(), upload_to='testimonials/profile_photos'),
        ),
    ]
