# Generated by Django 4.2.23 on 2026-02-20 12:42

import common.file_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0032_alter_qrmodel_qr_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='attachment',
            field=models.FileField(blank=True, default=None, null=True, storage=common.file_utils.CompanyFileStorage(), upload_to=common.file_utils.email_template_document_path),
        ),
        migrations.AlterField(
            model_name='qrmodel',
            name='qr_image',
            field=models.ImageField(blank=True, default=None, null=True, storage=common.file_utils.CompanyFileStorage(), upload_to=common.file_utils.qr_code_path),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='Profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, storage=common.file_utils.CompanyFileStorage(), upload_to=common.file_utils.testimonial_profile_photo_path),
        ),
    ]
