# Generated by Django 4.2.23 on 2026-02-23 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0033_alter_emailtemplate_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('plan', 'Plan'), ('addon', 'Addon')], default='plan', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='plan_pricing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.planpricing'),
        ),
        migrations.AlterField(
            model_name='bilinghistory',
            name='transaction_type',
            field=models.CharField(choices=[('plan_allocation', 'Plan Allocation'), ('addon', 'Addon')], max_length=20),
        ),
        migrations.CreateModel(
            name='AddonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('credits', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_plans', to='settings.feature')),
            ],
            options={
                'unique_together': {('feature', 'credits')},
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='addon_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.addonplan'),
        ),
    ]
