# Generated by Django 4.2.23 on 2026-02-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0034_payment_payment_type_payment_plan_pricing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingcycle',
            name='duration_in_months',
            field=models.FloatField(),
        ),
    ]
