# Generated by Django 4.2.23 on 2026-02-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0035_alter_billingcycle_duration_in_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
