# Generated by Django 4.2.23 on 2026-02-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0036_feature_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilinghistory',
            name='transaction_type',
            field=models.CharField(choices=[('plan_allocation', 'Plan Allocation'), ('addon', 'Addon'), ('custom_addon', 'Custom Addon')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('plan', 'Plan'), ('addon', 'Addon'), ('custom_addon', 'Custom Addon')], default='plan', max_length=20),
        ),
    ]
