# Generated by Django 4.2.23 on 2026-04-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0037_alter_bilinghistory_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatevariables',
            name='variables',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='variable'),
        ),
    ]
