"""
Django settings for edjobster project.
Generated by 'django-admin startproject' using Django 3.1.2.
For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import ssl
from pathlib import Path
import os
from datetime import timedelta
import environ

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, True),
    OPENAI_API_KEY=(str, '')
)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
CORE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# Load environment variables from .env file if it exists
env_file = os.path.join(BASE_DIR, '.env')
if os.path.exists(env_file):
    environ.Env.read_env(env_file)
else:
    # If .env file doesn't exist, try to get from environment variables
    os.environ.setdefault('OPENAI_API_KEY', '')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')
# In settings.py
Coresignal_API = env("Coresignal_API")  # This is correct as per your .env file

# SECRET_KEY= 'django-insecure-(1&l0)wxw70+f=gtuf%#_dl-i*83b_ey+dv#d8dbu_w$_cvsz+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'django_celery_beat',  # Celery Beat for scheduled tasks
    'common',
    'account',
    'settings',
    'job',
    'candidates',
    'interview',
    'hr_services',
    "letters",
    
    'django_cron',
    'drf_spectacular',
    'rest_framework_xml',
    'django.contrib.sitemaps',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = env.bool('CORS_ORIGIN_ALLOW_ALL', default=True)
CORS_ALLOW_ALL_ORIGINS = env.bool('CORS_ALLOW_ALL_ORIGINS', default=True)
CORS_ALLOW_CREDENTIALS = env.bool('CORS_ALLOW_CREDENTIALS', default=True)
CORS_ALLOW_METHODS = env.list('CORS_ALLOW_METHODS', default=[])
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[])
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])
# CORS_ALLOW_HEADERS = ('content-type', 'x-requested-with')

SPECTACULAR_SETTINGS = {
    "TITLE": "Ejobster",
    "DESCRIPTION": "Ejobster API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

CORS_ORIGIN_WHITELIST = env.list('CORS_ORIGIN_WHITELIST', default=[])

ROOT_URLCONF = 'edjobster.urls'

TEMPLATE_DIR = os.path.join(CORE_DIR, "common/templates")

# Base API URL (from .env)
# Example: API_URL=https://api.edjobster.com
API_URL = env('API_URL', default='https://api.edjobster.com')

# Base Frontend URL (from .env)
# Example: APP_URL=https://app.edjobster.com
APP_URL = env('APP_URL', default='https://app.edjobster.com')

# Careers site base URL (from .env)
# Example: JOB_URL=https://jobs.edjobster.com
JOB_URL = env('JOB_URL', default='https://jobs.edjobster.com')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'edjobster.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# POSTGRES_DB = os.environ.get("POSTGRES_DB") #database name
# print(POSTGRES_DB)
# POSTGRES_PASSWORD = os.environ.get("POSTGRES_PASSWORD") # database user password
# POSTGRES_USER = os.environ.get("POSTGRES_USER") # database username
# POSTGRES_HOST = os.environ.get("POSTGRES_HOST") # database host
# POSTGRES_PORT = os.environ.get("POSTGRES_PORT") # database port

# POSTGRES_READY = (
#     POSTGRES_DB is not None
#     and POSTGRES_PASSWORD is not None
#     and POSTGRES_USER is not None
#     and POSTGRES_HOST is not None
#     and POSTGRES_PORT is not None
# )

# if POSTGRES_READY:
#     DATABASES = {
#         "default": {
#             "ENGINE": "django.db.backends.postgresql",
#             "NAME": POSTGRES_DB,
#             "USER": POSTGRES_USER,
#             "PASSWORD": POSTGRES_PASSWORD,
#             "HOST": POSTGRES_HOST,
#             "PORT": POSTGRES_PORT,
#         }
#     }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('POSTGRES_DB'),  # database name
        'USER': env('POSTGRES_USER'),  # database username
        'PASSWORD': env('POSTGRES_PASSWORD'),  # database user password
        'HOST': env('POSTGRES_HOST'),  # database host
        'PORT': env('POSTGRES_PORT'),  # database port
    }
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

# STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

USER_PHOTO_URL = '/user-photo/'
USER_PHOTO_ROOT = os.path.join(BASE_DIR, 'media/users/')

AUTH_USER_MODEL = 'account.Account'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",

}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=14),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),
    'ROTATE_REFRESH_TOKEN': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer'),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=15),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}



EMAIL_BACKEND = 'django_smtp_ssl.SSLEmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
EMAIL_SSL=True
EMAIL_TLS=False

# Use configured host user as default sender
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# EMAIL_BACKEND = 'django_smtp_ssl.SSLEmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 465

# =======================
# Celery Configuration
# =======================
CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default="redis://localhost:6379/0")

# Proper SSL configuration for rediss://
if CELERY_BROKER_URL.startswith("rediss://"):
    CELERY_BROKER_USE_SSL = {
        'ssl_cert_reqs': ssl.CERT_NONE,
        'ssl_ca_certs': None,
        'ssl_certfile': None,
        'ssl_keyfile': None,
    }

if CELERY_RESULT_BACKEND.startswith("rediss://"):
    CELERY_RESULT_BACKEND_USE_SSL = {
        'ssl_cert_reqs': ssl.CERT_NONE,
        'ssl_ca_certs': None,
        'ssl_certfile': None,
        'ssl_keyfile': None,
    }

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

# Celery timezone
CELERY_ENABLE_UTC = False
CELERY_TIMEZONE = 'Asia/Kolkata'

# Additional Celery settings
CELERY_WORKER_CONCURRENCY = 4  # Number of concurrent workers
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000  # Restart workers after 1000 tasks
CELERY_TASK_ALWAYS_EAGER = False  # Set to True for testing/debugging
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_TASK_IGNORE_RESULT = False
CELERY_RESULT_EXPIRES = 3600  # Results expire after 1 hour



# Beat Configuration
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Task settings
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes


#RESUME PARSE
RESUME_PARSE_URL = "https://rest.rchilli.com/RChilliParser/Rchilli/parseResume"
RESUME_PARSE_BINARY_URL = "https://rest.rchilli.com/RChilliParser/Rchilli/parseResumeBinary"
RESUME_PARSE_USER = "Syed Hamid Hasan"
RESUME_PARSE_KEY = "NFSF6Y36"
RESUME_PARSE_VERSION = "8.0.0"

# OpenAI Settings
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')
if not OPENAI_API_KEY:
    logger.warning('OPENAI_API_KEY is not set. Resume parsing with AI will not work.')

#MEDIA URLS
RESUME_URL = '/cv/'
RESUME_URL_ROOT = os.path.join(BASE_DIR, 'media/resume/')
RESUME_FILE_URL = f"{API_URL}/candidate/cv/"


#LOGO URLS
LOGO_URL = '/media/'
LOGO_URL_ROOT = os.path.join(BASE_DIR, 'media')
LOGO_FILE_URL = f"{API_URL}/account/logo/"

#PHOTO URLS
PHOTO_URL = '/photos/'
PHOTO_URL_ROOT = os.path.join(BASE_DIR, 'media')
PHOTO_FILE_URL = f"{API_URL}/account/photo/"

JOB_DOC_URL = '/jd/'
JOB_DOC_URL_ROOT = os.path.join(BASE_DIR, 'media/jobs/')
JOB_DOC_FILE_URL = f"{API_URL}/jobs/jd/"


NOTE_ICON_URL = '/note-icon/'
NOTE_ICON_URL_ROOT = os.path.join(BASE_DIR, 'media/data/icons/')
NOTE_ICON_FILE_URL = f"{API_URL}/common/note-icon/"
    
APPEND_SLASH = False

JAZZMIN_SETTINGS = {
    # Title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "Edjobster Admin",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "Edjobster",

    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "Edjobster",

    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": "vendor/edjobster06.png",
    "login_logo": "vendor/edjobster09.png",

    # CSS classes that are applied to the logo above
    "site_logo_classes": "img-circle",

    # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
    "site_icon": None,

    # Welcome text on the login screen
    "welcome_sign": "Welcome to the Edjobster Admin",

    # Copyright on the footer
    "copyright": "Edjobster Ltd",

    # Custom CSS classes for the logo
    "site_logo_classes": "brand-image img-circle elevation-3",
    
    # Custom CSS files
    "custom_css": "custom_admin.css",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-outline-success"
    }
}

RAZORPAY_LIVE_MODE_KEY_ID = env('RAZORPAY_LIVE_MODE_KEY_ID')
RAZORPAY_LIVE_MODE_KEY_SECRET = env('RAZORPAY_LIVE_MODE_KEY_SECRET')
RAZORPAY_TEST_MODE_KEY_ID = env('RAZORPAY_TEST_MODE_KEY_ID')
RAZORPAY_TEST_MODE_KEY_SECRET = env('RAZORPAY_TEST_MODE_KEY_SECRET')
RAZORPAY_MODE = env('RAZORPAY_MODE')

ZOHO_CLIENT_ID = "1000.ZI8CYW0THCD8C5Y5LQQSFJ11FW9PGQ"
ZOHO_CLIENT_SECRET = "d478e3b78cfe798f4090d09f4081d68bba3ba8e8db"
ZOHO_REFRESH_TOKEN = "1000.a00e33b6314f15077058eaffd13e4fec.3ef4b2fdb37c38dd31b5aa0a2a0a74ab"
ZOHO_BASE_DOMAIN = "https://www.zohoapis.in"  # or .com / .eu
ZOHO_ACCOUNTS_URL = "https://accounts.zoho.in"  # or .com / .eu

try:
    from .local_settings import *
except ImportError:
    pass

JOB_URL = env('JOB_URL')