# Generated by Django 5.0.4 on 2024-11-13 13:26

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('settings', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssesmentCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Assesment Category',
                'verbose_name_plural': 'Assesment Categories',
            },
        ),
        migrations.CreateModel(
            name='Assesment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('form', models.JSONField(blank=True, default=None, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.assesmentcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Assesment',
                'verbose_name_plural': 'Assesments',
            },
        ),
        migrations.CreateModel(
            name='AssesmentQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('RADIO', 'Radio'), ('CHECK', 'Check'), ('SELECT', 'Select'), ('TEXT', 'Text')], default='RADIO', max_length=10)),
                ('question', models.TextField(max_length=500)),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('answer', models.CharField(max_length=100)),
                ('marks', models.IntegerField(default=1)),
                ('text', models.TextField(blank=True, max_length=1000, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('assesment', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='job.assesment', verbose_name='Assesment')),
            ],
            options={
                'verbose_name': 'AssesmentQuestion',
                'verbose_name_plural': 'AssesmentQuestions',
            },
        ),
        migrations.CreateModel(
            name='CompanyCredentials',
            fields=[
                ('board', models.CharField(choices=[('L', 'LINKEDIN')], default='L', max_length=2)),
                ('linkedIn_company_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='LinkedIn Company ID')),
                ('client_id', models.CharField(max_length=50, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=50, verbose_name='Client Secret')),
                ('auth_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='Auth Token')),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Company Credential',
                'verbose_name_plural': 'Company Credentials',
            },
        ),
        migrations.CreateModel(
            name='DraftJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('vacancies', models.IntegerField(blank=True, default=1, null=True)),
                ('members', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time')], default='FULL_TIME', max_length=20)),
                ('nature', models.CharField(choices=[('Physical', 'Physical'), ('Remote', 'Remote')], default='Physical', max_length=10)),
                ('educations', models.CharField(choices=[('HIGH_SCHOOL', 'HighSchool'), ('JUNIOR_COLLEGE', 'JuniorCollege'), ('BACHELORS', 'Bachelors'), ('MASTERS', 'Masters')], default='HIGH_SCHOOL', max_length=20, null=True)),
                ('speciality', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
                ('exp_min', models.IntegerField(blank=True, default=0, null=True)),
                ('exp_max', models.IntegerField(blank=True, default=0, null=True)),
                ('salary_min', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('salary_max', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('salary_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('document', models.FileField(blank=True, default=None, null=True, upload_to='media/draft_jobs/')),
                ('job_boards', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=False)),
                ('assesment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.assesment', verbose_name='Assesment')),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_draft_jobs', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.department', verbose_name='Department')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.location')),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_draft_jobs', to=settings.AUTH_USER_MODEL)),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_pipline_id', to='settings.pipeline')),
                ('webform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_webform_id', to='settings.webform')),
            ],
            options={
                'verbose_name': 'Draft Job',
                'verbose_name_plural': 'Draft Jobs',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('vacancies', models.IntegerField(blank=True, default=1, null=True)),
                ('members', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time')], default='FULL_TIME', max_length=20)),
                ('nature', models.CharField(choices=[('Physical', 'Physical'), ('Remote', 'Remote')], default='Physical', max_length=10)),
                ('educations', models.CharField(choices=[('HIGH_SCHOOL', 'HighSchool'), ('JUNIOR_COLLEGE', 'JuniorCollege'), ('BACHELORS', 'Bachelors'), ('MASTERS', 'Masters')], default='HIGH_SCHOOL', max_length=20, null=True)),
                ('speciality', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
                ('exp_min', models.IntegerField(blank=True, default=0, null=True)),
                ('exp_max', models.IntegerField(blank=True, default=0, null=True)),
                ('salary_min', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('salary_max', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('salary_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('job_status', models.CharField(blank=True, choices=[('In Progress', 'In Progress'), ('Filled', 'Filled'), ('On Hold', 'On Hold'), ('Closed', 'Closed')], default='In Progress', max_length=50, null=True)),
                ('document', models.FileField(blank=True, default=None, null=True, upload_to='media/jobs/')),
                ('job_boards', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=False)),
                ('assesment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.assesment', verbose_name='Assesment')),
                ('company', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.department', verbose_name='Department')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.location')),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_jobs', to=settings.AUTH_USER_MODEL)),
                ('pipeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipline_id', to='settings.pipeline')),
                ('webform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webform_id', to='settings.webform')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='JobNotes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, max_length=1000, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Added by')),
                ('job', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='job.job', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
    ]
