# Generated by Django 5.0.4 on 2024-11-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jobtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtitle',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
