# Generated by Django 5.0.4 on 2024-11-20 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_jobtitle_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobTitle',
        ),
    ]
