# Generated by Django 5.0.4 on 2024-12-17 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_delete_jobtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='speciality',
        ),
    ]
