# Generated by Django 5.0.4 on 2024-12-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_candidate_current_job_title_and_more'),
        ('job', '0005_remove_job_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='speciality',
            field=models.ManyToManyField(blank=True, to='candidates.skill'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
