# Generated by Django 5.0.4 on 2024-12-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_candidate_current_job_title_and_more'),
        ('job', '0006_job_speciality_alter_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftjob',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.RemoveField(
            model_name='draftjob',
            name='speciality',
        ),
        migrations.AddField(
            model_name='draftjob',
            name='speciality',
            field=models.ManyToManyField(blank=True, null=True, to='candidates.skill'),
        ),
    ]
