# Generated by Django 5.0.4 on 2025-01-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_draftjob_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
