# Generated by Django 5.0.4 on 2025-01-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_job_job_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='targetdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
