# Generated by Django 5.0.4 on 2025-01-31 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_job_startdate_job_targetdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='speciality',
        ),
    ]
