# Generated by Django 5.0.4 on 2025-01-31 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_remove_job_speciality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftjob',
            name='speciality',
        ),
    ]
