# Generated by Django 5.0.4 on 2025-01-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_draftjob_speciality_draftjob_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftjob',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
