# Generated by Django 5.0.4 on 2025-03-07 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_company_admin'),
        ('job', '0013_alter_draftjob_description_alter_job_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, max_length=1000, null=True)),
                ('access_token', models.CharField(blank=True, max_length=1000, null=True)),
                ('sub', models.CharField(blank=True, max_length=1000, null=True)),
                ('credentials', models.FileField(blank=True, default=None, null=True, upload_to='media/job_board_credentials/')),
                ('project_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('google_company_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_board', to='account.company')),
            ],
        ),
    ]
