# Generated by Django 5.0.4 on 2025-03-19 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_company_admin'),
        ('job', '0014_jobboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesmentcategory',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company', verbose_name='Company'),
        ),
    ]
