# Generated by Django 5.0.4 on 2025-04-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_alter_assesmentcategory_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='dynamic_job_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
