# Generated by Django 5.0.4 on 2025-05-01 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_job_dynamic_job_data'),
        ('settings', '0009_alter_webform_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='webform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webform_id', to='settings.webform'),
        ),
    ]
