# Generated by Django 5.0.4 on 2025-05-13 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_alter_job_webform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='educations',
        ),
        migrations.RemoveField(
            model_name='job',
            name='members',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_type',
        ),
    ]
