# Generated by Django 5.0.4 on 2025-05-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_remove_job_educations_remove_job_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assesment',
            name='dynamic_assessment_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
