# Generated by Django 5.0.4 on 2025-06-20 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0017_candidatetimeline'),
        ('interview', '0004_rename_webform_interview_data_interview_dynamic_interview_data'),
        ('job', '0019_assesment_dynamic_assessment_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTimeline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('CANDIDATE_CREATED', 'Candidate Created'), ('CANDIDATE_UPDATED', 'Candidate Updated'), ('JOB_UPDATED', 'Job Updated'), ('JOB_CREATED', 'Job Created'), ('STATUS_CHANGED', 'Status Changed'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('INTERVIEW_COMPLETED', 'Interview Completed'), ('NOTE_ADDED', 'Note Added'), ('JOB_ASSOCIATED', 'Job Associated'), ('JOB_SUBMITTED', 'Job Submitted'), ('CALL_LOGGED', 'Call Logged'), ('TASK_CREATED', 'Task Created'), ('EVENT_CREATED', 'Event Created'), ('EMAIL_SENT', 'Email Sent'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('ASSESSMENT_COMPLETED', 'Assessment Completed'), ('OFFER_MADE', 'Offer Made'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('OFFER_REJECTED', 'Offer Rejected'), ('HIRED', 'Hired'), ('ONBOARDED', 'Onboarded'), ('CANDIDATE_JOB_ASSIGNED', 'Candidate Job Assigned'), ('CANDIDATE_JOB_APPLIED', 'Candidate Job Applied')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('performed_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pipeline_stage_status', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_data', models.JSONField(blank=True, null=True)),
                ('old_status', models.CharField(blank=True, max_length=100, null=True)),
                ('new_status', models.CharField(blank=True, max_length=100, null=True)),
                ('activity_date', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate')),
                ('interview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interview.interview')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_timeline', to='job.job')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.call')),
                ('related_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.events')),
                ('related_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.note')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.tasks')),
            ],
        ),
    ]
