# Generated by Django 5.0.4 on 2025-06-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0020_jobtimeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtimeline',
            name='activity_type',
            field=models.CharField(choices=[('CANDIDATE_CREATED', 'Candidate Created'), ('CANDIDATE_UPDATED', 'Candidate Updated'), ('JOB_UPDATED', 'Job Updated'), ('JOB_CREATED', 'Job Created'), ('STATUS_CHANGED', 'Status Changed'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('INTERVIEW_COMPLETED', 'Interview Completed'), ('NOTE_ADDED', 'Note Added'), ('JOB_ASSOCIATED', 'Job Associated'), ('JOB_SUBMITTED', 'Job Submitted'), ('CALL_LOGGED', 'Call Logged'), ('TASK_CREATED', 'Task Created'), ('EVENT_CREATED', 'Event Created'), ('EMAIL_SENT', 'Email Sent'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('ASSESSMENT_COMPLETED', 'Assessment Completed'), ('OFFER_MADE', 'Offer Made'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('OFFER_REJECTED', 'Offer Rejected'), ('HIRED', 'Hired'), ('ONBOARDED', 'Onboarded'), ('CANDIDATE_JOB_ASSIGNED', 'Candidate Job Assigned'), ('CANDIDATE_JOB_APPLIED', 'Candidate Job Applied'), ('APPLIED', 'Applied')], max_length=50),
        ),
    ]
