# Generated by Django 5.0.4 on 2025-06-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0021_alter_jobtimeline_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftjob',
            name='dynamic_job_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
