# Generated by Django 5.0.4 on 2025-07-30 10:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0022_draftjob_dynamic_job_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_boards',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
