# Generated by Django 5.0.4 on 2025-08-13 05:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_company_admin'),
        ('job', '0023_alter_job_job_boards'),
        ('settings', '0016_emailtemplate_from_email_emailtemplate_reply_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DraftJob',
            new_name='TemplateJob',
        ),
    ]
