# Generated by Django 5.0.4 on 2025-08-13 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0024_rename_draftjob_templatejob'),
        ('settings', '0016_emailtemplate_from_email_emailtemplate_reply_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatejob',
            options={'verbose_name': 'Template Job', 'verbose_name_plural': 'Template Jobs'},
        ),
        migrations.AlterField(
            model_name='templatejob',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_template_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='templatejob',
            name='document',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/template_jobs/'),
        ),
        migrations.AlterField(
            model_name='templatejob',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_template_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='templatejob',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_pipline_id', to='settings.pipeline'),
        ),
        migrations.AlterField(
            model_name='templatejob',
            name='webform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_webform_id', to='settings.webform'),
        ),
    ]
