# Generated by Django 5.0.4 on 2025-08-13 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_company_admin'),
        ('job', '0025_alter_templatejob_options_and_more'),
        ('settings', '0016_emailtemplate_from_email_emailtemplate_reply_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftSaveJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dynamic_job_data', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('assesment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.assesment', verbose_name='Assesment')),
                ('company', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_draftsavejobs', to=settings.AUTH_USER_MODEL)),
                ('webform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_webform_id', to='settings.webform')),
            ],
            options={
                'verbose_name': 'draft Job',
                'verbose_name_plural': 'draft Jobs',
            },
        ),
    ]
