# Generated by Django 5.0.4 on 2025-08-13 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_company_admin'),
        ('job', '0026_draftsavejob'),
        ('settings', '0016_emailtemplate_from_email_emailtemplate_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftsavejob',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='draftsavejob',
            name='webform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_webform_id', to='settings.webform'),
        ),
    ]
