# Generated by Django 5.0.4 on 2025-08-20 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0027_alter_draftsavejob_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='speciality',
        ),
    ]
