# Generated by Django 5.0.4 on 2025-08-20 06:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0028_remove_job_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='speciality',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
