# Generated by Django 5.0.4 on 2025-08-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0029_job_speciality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='speciality',
        ),
        migrations.RemoveField(
            model_name='templatejob',
            name='vacancies',
        ),
    ]
