# Generated by Django 5.0.4 on 2025-10-10 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0030_remove_job_speciality_remove_templatejob_vacancies'),
        ('settings', '0016_emailtemplate_from_email_emailtemplate_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='assesment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.assesment', verbose_name='Assesment'),
        ),
        migrations.AlterField(
            model_name='job',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='job',
            name='pipeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipline_id', to='settings.pipeline'),
        ),
    ]
