# Generated by Django 4.2.23 on 2026-02-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0032_whatjobsjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatjobsjob',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
