# Generated by Django 4.2.23 on 2026-02-16 13:15

import common.file_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0033_whatjobsjob_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='document',
            field=models.FileField(blank=True, default=None, null=True, storage=common.file_utils.CompanyFileStorage(), upload_to=common.file_utils.job_document_path),
        ),
        migrations.AlterField(
            model_name='jobboard',
            name='credentials',
            field=models.FileField(blank=True, default=None, null=True, storage=common.file_utils.CompanyFileStorage(), upload_to=common.file_utils.job_board_credentials_path),
        ),
        migrations.AlterField(
            model_name='templatejob',
            name='document',
            field=models.FileField(blank=True, default=None, null=True, storage=common.file_utils.CompanyFileStorage(), upload_to='template_jobs/documents'),
        ),
    ]
