# Generated by Django 4.2.23 on 2026-02-20 12:42

import common.file_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0034_alter_job_document_alter_jobboard_credentials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatejob',
            name='document',
            field=models.FileField(blank=True, default=None, null=True, storage=common.file_utils.CompanyFileStorage(), upload_to='media/template_jobs/'),
        ),
    ]
